version: '3.6'

networks:
  matrix-network:
    driver: bridge

services:
  matrix-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - DB_HOST=matrix-postgres
      - REDIS_URL=matrix-redis
      - MONGO_URL=matrix-mongo
    depends_on:
      - matrix-postgres
      - matrix-mongo
    networks:
      - matrix-network
    container_name: matrix-api
    command: yarn dev:server
    ports:
      - '3333:3333'

  matrix-postgres:
    image: postgres
    container_name: matrix-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - matrix-network

  matrix-mongo:
    image: bitnami/mongodb:latest
    container_name: matrix-mongo
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - '27017:27017'
    networks:
      - matrix-network

  matrix-redis:
    image: bitnami/redis:latest
    container_name: matrix-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    networks:
      - matrix-network